/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qurandwnld;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author ibraheem
 */
public class DownloadMushafJFrame extends javax.swing.JFrame {

    private String all = "1 7 (01)\n"
            + "2 286 (40)\n"
            + "3 200 (20)\n"
            + "4 176 (24)\n"
            + "5 120 (16)\n"
            + "6 165 (20)\n"
            + "7 206 (24)\n"
            + "8 75 (10)\n"
            + "9 129 (16)\n"
            + "10 109 (11)\n"
            + "11 123 (10)\n"
            + "12 111 (12)\n"
            + "13 43 (06)\n"
            + "14 52 (07)\n"
            + "15 99 (06)\n"
            + "16 128 (16)\n"
            + "17 111 (12)\n"
            + "18 110 (12)\n"
            + "19 98 (06)\n"
            + "20 135 (08)\n"
            + "21 112 (07)\n"
            + "22 78 (10)\n"
            + "23 118 (06)\n"
            + "24 64 (09)\n"
            + "25 77 (06)\n"
            + "26 227 (11)\n"
            + "27 93 (07)\n"
            + "28 88 (09)\n"
            + "29 69 (07)\n"
            + "30 60 (06)\n"
            + "31 34\n"
            + "32 30\n"
            + "33 73\n"
            + "34 54\n"
            + "35 45\n"
            + "36 83\n"
            + "37 182\n"
            + "38 88\n"
            + "39 75\n"
            + "40 85\n"
            + "41 54\n"
            + "42 53\n"
            + "43 89\n"
            + "44 59\n"
            + "45 37\n"
            + "46 35\n"
            + "47 38\n"
            + "48 29\n"
            + "49 18\n"
            + "50 45\n"
            + "51 60\n"
            + "52 49\n"
            + "53 62\n"
            + "54 55\n"
            + "55 78\n"
            + "56 96\n"
            + "57 29\n"
            + "58 22\n"
            + "59 24\n"
            + "60 13\n"
            + "61 14\n"
            + "62 11\n"
            + "63 11\n"
            + "64 18 (02)\n"
            + "65 12 (02)\n"
            + "66 12 (02)\n"
            + "67 30 (02)\n"
            + "68 52 (02)\n"
            + "69 52 (02)\n"
            + "70 44 (02)\n"
            + "71 28 (02)\n"
            + "72 28 (02)\n"
            + "73 20 (02)\n"
            + "74 56 (02)\n"
            + "75 40 (02)\n"
            + "76 31 (02)\n"
            + "77 50 (02)\n"
            + "78 40 (02)\n"
            + "79 46 (02)\n"
            + "80 42 (01)\n"
            + "81 29 (01)\n"
            + "82 19 (01)\n"
            + "83 36 (01)\n"
            + "84 25 (01)\n"
            + "85 22 (01)\n"
            + "86 17 (01)\n"
            + "87 19 (01)\n"
            + "88 26 (01)\n"
            + "89 30 (01)\n"
            + "90 20 (01)\n"
            + "91 15 (01)\n"
            + "92 21 (01)\n"
            + "93 11 (01)\n"
            + "94 8 (01)\n"
            + "95 8 (01)\n"
            + "96 19 (01)\n"
            + "97 5 (01)\n"
            + "98 8 (01)\n"
            + "99 8 (01)\n"
            + "100 11 (01)\n"
            + "101 11 (01)\n"
            + "102 8 (01)\n"
            + "103 3 (01)\n"
            + "104 9 (01)\n"
            + "105 5 (01)\n"
            + "106 4 (01)\n"
            + "107 7 (01)\n"
            + "108 3 (01)\n"
            + "109 6 (01)\n"
            + "110 3 (01)\n"
            + "111 5 (01)\n"
            + "112 4 (01)\n"
            + "113 5 (05)\n"
            + "114 6 (01)";

    private final int[] ayaat;

    /**
     * Creates new form NewJFrame
     */
    public DownloadMushafJFrame() {
        initComponents();
        ayaat = new int[114];
        String[] arr = all.split("\n");
        for (int i = 0; i < arr.length; i++) {
            String[] m = arr[i].split(" ");
            //System.out.println(m[0] + " " + m[1]);
            //int s = Integer.parseInt(m.group(1));
            int a = Integer.parseInt(m[1]);
            ayaat[i] = a;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton1)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Thread(
                new Runnable() {

            @Override
            public void run() {
                final byte data[] = new byte[1024];                
                File dir = new File("C:\\Users\\ibraheem\\Downloads\\quran\\parts\\");
                for (int s = 0; s < ayaat.length; ++s) {
                    int sur = s + 1;
                    int ayat = ayaat[s];
                    for (int a = 1; a <= ayat; ++a) {
                        try {
                            //Path dir = Files.createDirectories(new File("/ayaat").toPath());
                            File d = new File(dir, "" + sur);
                            d.mkdir();
                            URL website = new URL(String.format("http://www.everyayah.com/data/quranpngs/%d_%d.png",
                                    sur, a));
                                jProgressBar1.setValue(sur * 100 / 114);
                                jProgressBar2.setValue(a * 100 / ayat);
//                            try (BufferedInputStream in = new BufferedInputStream(website.openStream());
//                                    FileOutputStream fout = new FileOutputStream(new File(d, a + ".png"))) {
//                                int count;
//                                while ((count = in.read(data, 0, 1024)) != -1) {
//                                    fout.write(data, 0, count);
//                                }
//                            }
                    try (ReadableByteChannel rbc = Channels.newChannel(website.openStream());
                            FileOutputStream fos = new FileOutputStream(new File(d, a + ".png"))) {
                        jProgressBar1.setValue(sur * 100 / 114);
                        jProgressBar2.setValue(a * 100 / ayat);
                        fos.getChannel().transferFrom(rbc, 0, Long.MAX_VALUE);
                    }
                        } catch (MalformedURLException ex) {
                            Logger.getLogger(DownloadMushafJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(DownloadMushafJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }).start();
                        //.run();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DownloadMushafJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DownloadMushafJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DownloadMushafJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DownloadMushafJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DownloadMushafJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables
}
