/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qurandwnld;

import java.awt.Frame;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.SpinnerNumberModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Yasser
 */
public class EditSelectionJPanel extends javax.swing.JDialog {

    private Selection selection;
    
    /**
     * Creates new form EditSelectionJPanel
     */
    public EditSelectionJPanel(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jComboBoxSurah.setModel(new DefaultComboBoxModel(QuranData.surahName));
        AutoCompleteDecorator.decorate(jComboBoxSurah);
    }
    
    public void set(Selection s) {
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.clear();
        if (s.details == null)
            s.details = new ArrayList<>();
        for (SelectionDetail d : s.details)
            model.addElement(d);
        jTextField1.setText(s.ayahWord);
        Point p = DbHelper.getAyah(s.ayahIndex);
        jComboBoxSurah.setSelectedIndex(p.x - 1);
        jSpinnerAyah.setValue(p.y);
        selection = s;
    }
    
    
    void editSelectionDetail(SelectionDetail s) {
        InputQeraatJDialog j = new InputQeraatJDialog((Frame) this.getParent(), true);
        j.set(s);
        JOptionPane.showMessageDialog(this, j.getContentPane(), "تحرير بيانات القراءة",
                JOptionPane.PLAIN_MESSAGE);
        j.get();
        //DbHelper.updateSelectionDetail(s);
    }
    
    
    public Selection get() {
        selection.ayahIndex = DbHelper.getAyahIndex(jComboBoxSurah.getSelectedIndex() + 1, 
                (int) jSpinnerAyah.getValue());
        selection.ayahWord = jTextField1.getText();
        selection.details.clear();
        for (int i = 0; i < jList1.getModel().getSize(); ++i) {
            selection.details.add((SelectionDetail) jList1.getModel().getElementAt(i));
        }
        return selection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxSurah = new javax.swing.JComboBox();
        jSpinnerAyah = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jMenuItem1.setText("تعديل...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("إزالة");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);
        jPopupMenu1.add(jSeparator1);

        jMenuItem3.setText("جديد");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jLabel1.setText("السورة:");

        jLabel2.setText("الآية");

        jComboBoxSurah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSpinnerAyah.setModel(new SpinnerNumberModel(1, 1, 286, 1));

        jList1.setModel(new javax.swing.DefaultListModel<Object>());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setToolTipText("");
        jList1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jList1);

        jLabel3.setText("موضع الخلاف في الآية:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSpinnerAyah, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxSurah, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxSurah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerAyah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        SelectionDetail d = (SelectionDetail) jList1.getSelectedValue();
        if (d == null) return;
        QeraatGroupJPanel j = new QeraatGroupJPanel();
        j.set(d);
        if (JOptionPane.showConfirmDialog(getParent(),
                        j,
                        "تحرير بيانات القراءة",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
            j.get();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        SelectionDetail d = (SelectionDetail) jList1.getSelectedValue();
        if (d == null) return;
        if (JOptionPane.showConfirmDialog(this, "حذف الخلاف المحدد؟")
                == JOptionPane.OK_OPTION) {
            ((DefaultListModel) jList1.getModel()).removeElement(d);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        QeraatGroupJPanel j = new QeraatGroupJPanel();
        SelectionDetail d = new SelectionDetail();
        d.type = SelectionType.Farsh;
        d.descr = "";
        d.shatibiyyah = new ArrayList<>();
        d.dorrah = new ArrayList<>();
        d.rewayaat = new RewayahSelectionList();
        j.set(d);
        if (JOptionPane.showConfirmDialog(getParent(),
                        j,
                        "تحرير بيانات القراءة",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
            d = j.get();
            ((DefaultListModel) jList1.getModel()).addElement(d);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxSurah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSpinner jSpinnerAyah;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
