/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qurandwnld;

import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ibraheem
 */
public class InputQeraatJDialog extends javax.swing.JDialog {
    
    private Selection lastSelection;
    
    void set(Selection s) {
        lastSelection = s;
        switch (s.type) {
            case Edgham:
                jLabel1.setText("النوع: إدغام");
                break;
            case Emalah:
                jLabel1.setText("النوع: إمالة");
                break;
            case Farsh:
                jLabel1.setText("النوع: فرش");
                break;
            case Hamz:
                jLabel1.setText("النوع: همز");
                break;
            case Mad:
                jLabel1.setText("النوع: مد");
                break;
            case Naql:
                jLabel1.setText("النوع: نقل");
                break;
            case Sakt:
                jLabel1.setText("النوع: سكت");
                break;
        }
        if (s.khelafat != null) 
            for (RewayahSelectionGroup g : s.khelafat)
                ((DefaultListModel) jList1.getModel()).addElement(g);
        jTextArea2.setText(s.shahed);
    }
    
    Selection get() {
        Selection s = lastSelection;
        s.shahed = jTextArea2.getText();
        if (s.khelafat == null || s.khelafat.length != jList1.getModel().getSize())
            s.khelafat = new RewayahSelectionGroup[jList1.getModel().getSize()];
        for (int i = 0; i < jList1.getModel().getSize(); ++i) {
            s.khelafat[i] = (RewayahSelectionGroup) jList1.getModel().getElementAt(i);
        }
        return s;
    }
    
    /**
     * Creates new form NewJDialog
     */
    public InputQeraatJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        WriteJFrame1.rtlLayout(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();

        jMenuItem1.setText("إزالة");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("تعديل");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("إضافة جديد");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("تحرير بيانات القراءة");

        jLabel3.setText("الشاهد");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        jList1.setModel(new DefaultListModel<>());
        jList1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("الخلافات");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int[] s = jList1.getSelectedIndices();
        if (s.length > 0 && JOptionPane.showConfirmDialog(this, "متأكد من حذف الخلافات المحددة؟")
                == JOptionPane.OK_OPTION) {
            Arrays.sort(s);
            for (int i = s.length - 1; i >= 0; --i) {
                ((DefaultListModel) jList1.getModel()).removeElementAt(s[i]);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        RewayahSelectionGroup sel = (RewayahSelectionGroup) jList1.getSelectedValue();
        if (sel != null) {
            QeraatGroupJPanel j = new QeraatGroupJPanel();
            j.set(sel);
            if (JOptionPane.showConfirmDialog(this, j, "تحرير بيانات القراءة",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
                j.get();
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        RewayahSelectionGroup sel = new RewayahSelectionGroup();
        QeraatGroupJPanel j = new QeraatGroupJPanel();
        j.set(sel);
        if (JOptionPane.showConfirmDialog(this, j, "تحرير بيانات القراءة",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
            ((DefaultListModel) jList1.getModel()).addElement(j.get());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
