/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qurandwnld;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Function;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ibraheem
 */
public class InputQeraatJDialog extends javax.swing.JDialog {
    
    private SelectionDetail lastSelection;
    
    void set(SelectionDetail s) {
        lastSelection = s;
        switch (s.type) {
            case Edgham:
                jLabel1.setText("النوع: إدغام");
                break;
            case Emalah:
                jLabel1.setText("النوع: إمالة");
                break;
            case Farsh:
                jLabel1.setText("النوع: فرش");
                break;
            case Hamz:
                jLabel1.setText("النوع: همز");
                break;
            case Mad:
                jLabel1.setText("النوع: مد");
                break;
            case Naql:
                jLabel1.setText("النوع: نقل");
                break;
            case Sakt:
                jLabel1.setText("النوع: سكت");
                break;
        }
        if (s.rewayaat != null) 
            for (Rewayah g : s.rewayaat)
                ((DefaultListModel) jList1.getModel()).addElement(g);
        updateShahedText(lastSelection);
    }
    
    SelectionDetail get() {
        SelectionDetail s = lastSelection;
        //s.shahed = jTextArea2.getText();
        if (s.rewayaat == null || s.rewayaat.size() != jList1.getModel().getSize())
            s.rewayaat = new RewayahSelectionList();
        for (int i = 0; i < jList1.getModel().getSize(); ++i) {
            s.rewayaat.add((Rewayah) jList1.getModel().getElementAt(i));
        }
        return s;
    }
    
    /**
     * Creates new form NewJDialog
     */
    public InputQeraatJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        WriteJFrame1.rtlLayout(this);
    }

    private void updateShahedText(SelectionDetail s) {
        StringBuilder b = new StringBuilder();
        Function<String, String> str = t -> t == null ? "      " : t.trim();
        if (s != null) {
            if (s.shatibiyyah != null && !s.shatibiyyah.isEmpty()) {
                b.append("من الشاطبية:\n");
                for (Shahed h : s.shatibiyyah)
                    b.append(h.id).append(". ").append(str.apply(h.part1))
                            .append(" ... ").append(str.apply(h.part2))
                            .append("\n");
                b.append("\n");
            }
            if (s.dorrah != null && !s.dorrah.isEmpty()) {
                b.append("من الدرة:\n");
                for (Shahed h : s.dorrah)
                    b.append(h.id).append(". ").append(str.apply(h.part1))
                            .append(" ... ").append(str.apply(h.part2))
                            .append("\n");
            }
        }
        jTextArea2.setText(b.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();

        jMenuItem1.setText("إزالة");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("تعديل");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("إضافة جديد");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem4.setText("من الشاطبية...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem4);

        jMenuItem5.setText("من الدرة...");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("تحرير بيانات القراءة");

        jLabel3.setText("الشاهد");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setComponentPopupMenu(jPopupMenu2);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        jList1.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jList1.setModel(new DefaultListModel<>());
        jList1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("الخلافات");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int[] s = jList1.getSelectedIndices();
        if (s.length > 0 && JOptionPane.showConfirmDialog(this, "متأكد من حذف الخلافات المحددة؟")
                == JOptionPane.OK_OPTION) {
            Arrays.sort(s);
            for (int i = s.length - 1; i >= 0; --i) {
                ((DefaultListModel) jList1.getModel()).removeElementAt(s[i]);
                //TODO:
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        SelectionDetail sel = (SelectionDetail) jList1.getSelectedValue();
        if (sel != null) {
            QeraatGroupJPanel j = new QeraatGroupJPanel();
            j.set(sel);
            if (JOptionPane.showConfirmDialog(this, j, "تحرير بيانات القراءة",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
                j.get();
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SelectionDetail sel = new SelectionDetail();
        QeraatGroupJPanel j = new QeraatGroupJPanel();
        j.set(sel);
        if (JOptionPane.showConfirmDialog(this, j, "تحرير بيانات القراءة",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION) {
            ((DefaultListModel) jList1.getModel()).addElement(j.get());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private boolean compare(Map<Integer, Byte> sel1, Map<Integer, Byte> sel2) {
        if (sel1.size() != sel2.size()) return false;
        boolean yes = true;
        for (Map.Entry<Integer, Byte> k : sel1.entrySet()) {
            Byte get = sel2.get(k.getKey());
            if (!Objects.equals(get, k.getValue())) {
                yes = false;
                break;
            }
        }
        return yes;
    }
    
    private void work(boolean isDorrah, SelectionDetail detail) {
        Map<Integer, Byte> init = new LinkedHashMap<>();
        if (detail.dorrah == null)
            detail.dorrah = new ArrayList<>();
        if (detail.shatibiyyah == null)
            detail.shatibiyyah = new ArrayList<>();
        ArrayList<Shahed> list = isDorrah ? detail.dorrah : detail.shatibiyyah;
        if (list != null)
            list.stream().forEach(k -> {
                init.put(k.id, k.part2 == null ? ChooseShahedJFrame.SELECTION_PART1 : 
                        k.part1 == null ? ChooseShahedJFrame.SELECTION_PART2 : ChooseShahedJFrame.SELECTION_ALL);
            });
        int page = 1;
        if (!init.isEmpty()) {
            int beit = init.entrySet().iterator().next().getKey();
            page = DbHelper.getMatnPageByBeit(beit, isDorrah);
        }
        ChooseShahedJFrame frame = new ChooseShahedJFrame(isDorrah, page);
        frame.addSelections(init);
        if (JOptionPane.showConfirmDialog(this, frame.getContentPane(), "تحديد الشاهد",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            Map<Integer, Byte> sel = frame.getSelections();
            if (!compare(init, sel)) {
                List<Integer> ids = sel.keySet().stream().collect(Collectors.toList());
                ids.sort((i, j) -> i.compareTo(j));
                ArrayList<Shahed> sh = DbHelper.getShahedList(ids, isDorrah);
                list.clear();
                sh.stream().forEach(h -> {
                    switch (sel.get(h.id)) {
                        case ChooseShahedJFrame.SELECTION_ALL:
                            break;
                        case ChooseShahedJFrame.SELECTION_PART1:
                            h.part2 = null;
                            break;
                        case ChooseShahedJFrame.SELECTION_PART2:
                            h.part1 = null;
                            break;
                    }
                    list.add(h);
                });
                //TODO: DbHelper.updateSelectionDetailShahed(detail);
                updateShahedText(lastSelection);
            }
        }
    }
    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        work(false, lastSelection);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        work(true, lastSelection);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
