/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qurandwnld;

import java.awt.event.ActionEvent;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;

/**
 *
 * @author ibraheem
 */
public class QeraatGroupJPanel extends javax.swing.JPanel {

    private final RewayahSelectionGroup temp = new RewayahSelectionGroup();
    private RewayahSelectionGroup current;
    
    /**
     * Creates new form QeraatGroupJPanel
     */
    public QeraatGroupJPanel() {
        initComponents();
        initMenues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuQeraat = new javax.swing.JPopupMenu();
        jMenuRewayat = new javax.swing.JPopupMenu();
        jMenuRamz = new javax.swing.JPopupMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabelPreview = new javax.swing.JLabel();

        jMenuItem1.setText("إزالة");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jLabel2.setText("الوصف");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jList1.setModel(new DefaultListModel<RewayahSelection>());
        jList1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane2.setViewportView(jList1);

        jLabel1.setText("الروايات");

        jButton1.setText("المحدد بغير خلف");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("المحدد بخلف");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("إضافة قارئ");
        jButton3.setComponentPopupMenu(jMenuQeraat);

        jButton4.setText("إضافة رواية");
        jButton4.setComponentPopupMenu(jMenuRewayat);

        jButton5.setText("إضافة رمز");
        jButton5.setComponentPopupMenu(jMenuRamz);

        jLabelPreview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        List<RewayahSelection> l = jList1.getSelectedValuesList();
        for (int i = 0; i < l.size(); ++i) {
            RewayahSelection s = l.get(i);
            s.kholf = true;
        }
        jList1.invalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<RewayahSelection> l = jList1.getSelectedValuesList();
        for (int i = 0; i < l.size(); ++i) {
            RewayahSelection s = l.get(i);
            s.kholf = false;
        }
        jList1.invalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int[] s = jList1.getSelectedIndices();
        Arrays.sort(s);
        for (int i = s.length - 1; i >= 0; --i) {
            ((DefaultListModel) jList1.getModel()).removeElementAt(s[i]);
        }
        get(temp);
        jLabelPreview.setText(temp.toString());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    void set(RewayahSelectionGroup s) {
        jTextArea1.setText(s.descr);
        if (s.rewayaat != null) {
            for (RewayahSelection r : s.rewayaat) {
                addListItem(r);
            }
        }
        current = s;
        jLabelPreview.setText(current.toString());
    }
    
    void get(RewayahSelectionGroup current) {
        current.descr = jTextArea1.getText();
        current.rewayaat = new RewayahSelection[jList1.getModel().getSize()];
        for (int i = 0; i < jList1.getModel().getSize(); ++i) {
            current.rewayaat[i] = (RewayahSelection) jList1.getModel().getElementAt(i);
        }
    }
    
    RewayahSelectionGroup get() {
        get(current);
        return current;
    }
    
    private void addListItem(RewayahSelection r) {
        ((DefaultListModel) jList1.getModel()).addElement(r);
    }
    
    private void addRewayah(Rewayah r) {
        for (int i = 0; i < jList1.getModel().getSize(); ++i) {
            if (((RewayahSelection) jList1.getModel().getElementAt(i)).r == r)
                return;
        }
        RewayahSelection s = new RewayahSelection();
        s.r = r;
        addListItem(s);
        jLabelPreview.setText(current.toString());
    }
    
    private void addItem(Object o) {
        if (o instanceof Qeraah) {
            Qeraah q = (Qeraah) o;
            for (int i = 0; i < Rewayah.array.length; ++i) {
                if (Rewayah.array[i].qeraah == q)
                    addRewayah(Rewayah.array[i]);
            }
        } else if (o instanceof Rewayah) {
            addRewayah((Rewayah) o);
        } else if (o instanceof QeraahGroup) {
            QeraahGroup g = (QeraahGroup) o;
            for (Qeraah q : g.qeraat)
                addItem(q);
        }
        get(temp);
        jLabelPreview.setText(temp.toString());
    }
    
    private void initMenues() {
        for (int i = 0; i < Qeraah.array.length; ++i) {
            JMenuItem item = new JMenuItem(Qeraah.array[i].qeraah);
            item.setArmed(true);
            final Qeraah tmp = Qeraah.array[i];
            item.addActionListener((ActionEvent e) -> addItem(tmp));
            jMenuQeraat.add(item);
        }
        for (int i = 0; i < Rewayah.array.length; ++i) {
            JMenuItem item = new JMenuItem(Rewayah.array[i].rewayah);
            item.setArmed(true);
            final Rewayah tmp = Rewayah.array[i];
            item.addActionListener((ActionEvent e) -> addItem(tmp));
            jMenuRewayat.add(item);
        }
        for (int i = 0; i < QeraahGroup.array.length; ++i) {
            JMenuItem item = new JMenuItem(QeraahGroup.array[i].name);
            item.setArmed(true);
            final QeraahGroup tmp = QeraahGroup.array[i];
            item.addActionListener((ActionEvent e) -> addItem(tmp));
            jMenuRamz.add(item);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPreview;
    private javax.swing.JList jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jMenuQeraat;
    private javax.swing.JPopupMenu jMenuRamz;
    private javax.swing.JPopupMenu jMenuRewayat;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
final class Qeraah {
    public static final Qeraah NAFE3 = new Qeraah("نافع", "1");
    public static final Qeraah IBN_KATHEER = new Qeraah("ابن كثير", "2");
    public static final Qeraah ABO_AMRE = new Qeraah("أبو عمرو", "3");
    public static final Qeraah IBN_AMER = new Qeraah("ابن عامر", "4");
    public static final Qeraah AASEM = new Qeraah("عاصم", "5");
    public static final Qeraah HAMZAH = new Qeraah("حمزة", "6");
    public static final Qeraah ALKESA2E = new Qeraah("الكسائي", "7");
    public static final Qeraah ABO_JA3FAR = new Qeraah("أبو جعفر", "8");
    public static final Qeraah YA3QOB = new Qeraah("يعقوب", "9");
    public static final Qeraah KHALAF = new Qeraah("خلف العاشر", "10");
    
    public static final Qeraah[] array = {Qeraah.NAFE3,Qeraah.IBN_KATHEER,Qeraah.ABO_AMRE,Qeraah.IBN_AMER,
            Qeraah.AASEM,Qeraah.HAMZAH,Qeraah.ALKESA2E,Qeraah.ABO_JA3FAR,Qeraah.YA3QOB,Qeraah.KHALAF};
    
    public final String qeraah, code;
    
    private Qeraah(String q, String code) {
        this.qeraah = q;
        this.code = code;
    }

    @Override
    public String toString() {
        return qeraah;
    }
}

final class Rewayah {
    public static final Rewayah QALOON = new Rewayah(Qeraah.NAFE3, "قالون", "1");
    public static final Rewayah WARSH = new Rewayah(Qeraah.NAFE3, "ورش", "2");
    public static final Rewayah BAZZI = new Rewayah(Qeraah.IBN_KATHEER, "البزي", "1");
    public static final Rewayah QONBOL = new Rewayah(Qeraah.IBN_KATHEER, "قنبل", "2");
    public static final Rewayah DORI_ABO_AMR = new Rewayah(Qeraah.ABO_AMRE, "الدوري", "1");
    public static final Rewayah SOSI = new Rewayah(Qeraah.ABO_AMRE, "السوسي", "2");
    public static final Rewayah IBN_THAKWAN = new Rewayah(Qeraah.IBN_AMER, "ابن ذكوان", "1");
    public static final Rewayah HESHAM = new Rewayah(Qeraah.IBN_AMER, "هشام", "2");
    public static final Rewayah SHO3BAH = new Rewayah(Qeraah.AASEM, "شعبة", "1");
    public static final Rewayah HAFS = new Rewayah(Qeraah.AASEM, "حفص", "2");
    public static final Rewayah KHALAF = new Rewayah(Qeraah.HAMZAH, "خلف", "1");
    public static final Rewayah KHALLAD = new Rewayah(Qeraah.HAMZAH, "خلاد", "2");
    public static final Rewayah ABO_ALHARETH = new Rewayah(Qeraah.ALKESA2E, "أبو الحارث", "1");
    public static final Rewayah DORI_KESA2E = new Rewayah(Qeraah.ALKESA2E, "الدوري", "2");
    public static final Rewayah IBN_WARDAN = new Rewayah(Qeraah.ABO_JA3FAR, "ابن وردان", "1");
    public static final Rewayah IBN_JAMMAZ = new Rewayah(Qeraah.ABO_JA3FAR, "ابن جماز", "2");
    public static final Rewayah ROWISE = new Rewayah(Qeraah.YA3QOB, "رويس", "1");
    public static final Rewayah ROW7 = new Rewayah(Qeraah.YA3QOB, "روح", "2");
    public static final Rewayah ES7AQ = new Rewayah(Qeraah.KHALAF, "إسحاق", "1");
    public static final Rewayah EDREES = new Rewayah(Qeraah.KHALAF, "إدريس", "2");
    
    public static final Rewayah[] array = {
        QALOON,WARSH,BAZZI,QONBOL,DORI_ABO_AMR,SOSI,HESHAM,IBN_THAKWAN,
        SHO3BAH,HAFS,KHALAF,KHALLAD,ABO_ALHARETH,DORI_KESA2E,
        IBN_WARDAN,IBN_JAMMAZ,ROWISE,ROW7,ES7AQ,EDREES
    };
    
    public static boolean toStringUsesCode = false;
    
    public static Rewayah getByCombinedCode(String c) {
        for (Rewayah r : array) {
            if (r.getCombinedCode().equals(c))
                return r;
        }
        throw new IllegalArgumentException();
    }
    
    public final String rewayah, code;
    public final Qeraah qeraah;
    
    private Rewayah(Qeraah q, String rewayah, String code) {
        this.qeraah = q;
        this.rewayah = rewayah;
        this.code = code;
    }
    
    public String getCombinedCode() {
        return qeraah.code + "." + code;
    }
    
    public String getCombinedName() {
        return rewayah + " عن " + (qeraah.qeraah.startsWith("أبو") ?
                "أبي" + qeraah.qeraah.substring(3) : qeraah.qeraah);
    }

    @Override
    public String toString() {
        return toStringUsesCode ? getCombinedCode() : getCombinedName();
    }
}

final class QeraahGroup {
    public static final QeraahGroup SAMA = new QeraahGroup("سما", new Qeraah[]{Qeraah.NAFE3,Qeraah.IBN_KATHEER,Qeraah.ABO_AMRE});
    public static final QeraahGroup NAFAR = new QeraahGroup("نفر", new Qeraah[]{Qeraah.IBN_KATHEER,Qeraah.ABO_AMRE,Qeraah.IBN_AMER});
    public static final QeraahGroup HAQQ = new QeraahGroup("حق", new Qeraah[]{Qeraah.IBN_KATHEER,Qeraah.ABO_AMRE});
    public static final QeraahGroup AMMA = new QeraahGroup("عم", new Qeraah[]{Qeraah.NAFE3,Qeraah.IBN_AMER});
    public static final QeraahGroup THAL = new QeraahGroup("ذ", new Qeraah[]{Qeraah.AASEM,Qeraah.HAMZAH,Qeraah.ALKESA2E,Qeraah.IBN_AMER});
    public static final QeraahGroup ZHAA = new QeraahGroup("ظ", new Qeraah[]{Qeraah.AASEM,Qeraah.HAMZAH,Qeraah.ALKESA2E,Qeraah.IBN_KATHEER});
    public static final QeraahGroup KHAA = new QeraahGroup("خ", new Qeraah[]{Qeraah.IBN_KATHEER,Qeraah.ABO_AMRE,Qeraah.IBN_AMER,Qeraah.AASEM,Qeraah.HAMZAH,Qeraah.ALKESA2E});
    public static final QeraahGroup KOFI = new QeraahGroup("الكوفي", new Qeraah[]{Qeraah.AASEM,Qeraah.HAMZAH,Qeraah.ALKESA2E});
    public static final QeraahGroup GHINE = new QeraahGroup("غ", new Qeraah[]{Qeraah.AASEM,Qeraah.HAMZAH,Qeraah.ALKESA2E,Qeraah.ABO_AMRE});
    
    public static final QeraahGroup[] array = {SAMA,NAFAR,HAQQ,AMMA,THAL,ZHAA,KHAA,KOFI,GHINE};
    
    public final String name;
    public final Qeraah[] qeraat;

    private QeraahGroup(String name, Qeraah[] qeraat) {
        this.name = name;
        this.qeraat = qeraat;
    }
}

class RewayahSelection {
    Rewayah r;
    boolean kholf;

    @Override
    public String toString() {
        return r.getCombinedName() + (kholf ? " ؟" : "");
    }
}

class RewayahSelectionGroup {
    RewayahSelection[] rewayaat;
    String descr;
    
    private boolean applies(List<RewayahSelection> l, Rewayah r) {
        return l.stream().anyMatch((RewayahSelection s) -> {
           return s.r == r && !s.kholf; 
        });
    }
    
    private void remove(List<RewayahSelection> l, Rewayah r) {
        Object[] rem = l.stream().filter((s) -> (s.r == r)).toArray();
        l.removeAll(Arrays.asList(rem));
    }
    
    private boolean applies(List<RewayahSelection> l, Qeraah q) {
        Object[] o = Arrays.stream(Rewayah.array).filter((Rewayah t) -> {
            return t.qeraah == q;
        }).toArray();
        return Arrays.stream(o).allMatch((Object s) -> {
            return applies(l, (Rewayah) s);
        });
    }
    
    private void remove(List<RewayahSelection> l, Qeraah r) {
        Object[] rem = l.stream().filter((s) -> (s.r.qeraah == r)).toArray();
        l.removeAll(Arrays.asList(rem));
    }
    
    private boolean applies(List<RewayahSelection> l, QeraahGroup g) {
        return Arrays.stream(g.qeraat).allMatch((Qeraah q) -> {
            return applies(l, q);
        });
    }
    
    private void remove(List<RewayahSelection> l, QeraahGroup r) {
        for (Qeraah q : r.qeraat) {
            remove(l, q);
        }
    }
    
    private StringBuilder tryGroup() {
        // 1. try group by ramz, then qeraah (if no kholf)
        // 2. sort qeraat, rewayaat
        StringBuilder ret = new StringBuilder();
        List<RewayahSelection> l = new LinkedList<>(Arrays.asList(rewayaat));
        for (QeraahGroup g : QeraahGroup.array) {
            if (applies(l, g)) {
                remove(l, g);
                if (ret.length() > 0)
                    ret.append(" و");
                if (g == QeraahGroup.KOFI)
                    ret.append("الكوفيون");
                else
                    ret.append("أهل ").append(g.name);
            }
        }
        for (Qeraah g : Qeraah.array) {
            if (applies(l, g)) {
                remove(l, g);
                if (ret.length() > 0)
                    ret.append(" و");
                ret.append(g.toString());
            }
        }
        for (Rewayah g : Rewayah.array) {
            if (applies(l, g)) {
                remove(l, g);
                if (ret.length() > 0)
                    ret.append(" و");
                ret.append(g.toString());
            }
        }
        for (RewayahSelection s : l) {
            if (ret.length() > 0)
                ret.append(" و");
            ret.append(s.r.toString());
            if (s.kholf)
                ret.append(" بخلف عنه");
        }
        return ret;
    }

    @Override
    public String toString() {
        return "قرأ " + tryGroup() + " بـ " + descr;
    }
}