/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qurandwnld;

import java.awt.Dimension;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Yasser
 */
class ResizeSelectionJPanel extends javax.swing.JPanel {

    private final double x1, y1, x2, y2;
    private final Selection s;
    private final PaintSurface surface;
    
    private double curX, curY;
    
    public ResizeSelectionJPanel(Selection s, PaintSurface surface) {
        initComponents();
        this.s = s;
        this.surface = surface;
        //if (s instanceof RectSelection) {
            //RectSelection ss = (RectSelection) s;
            Rectangle2D.Float rect = (Rectangle2D.Float) s.scaledRect;
            x1 = rect.getX();
            y1 = rect.getY();
            x2 = rect.getWidth();
            y2 = rect.getHeight();
//        } else {
//            LineSelection ss = (LineSelection) s;
//            Line2D.Float line = (Line2D.Float) ss.line;
//            x1 = line.getX1();
//            y1 = line.getY1();
//            x2 = line.getX2();
//            y2 = line.getY2();
//        }
        curX = x2;
        curY = y2;
        jSpinner1.setModel(new SpinnerNumberModel(x2, 1, 500, 0.5));
        jSpinner1.addChangeListener((ChangeEvent e) -> {
            update(curX = (double) jSpinner1.getValue(), curY);
        });
        jSpinner2.setModel(new SpinnerNumberModel(y2, 1, 500, 0.5));
        //if (s instanceof LineSelection)
        //    jSpinner2.setEnabled(false);
        //else 
        jSpinner2.addChangeListener((ChangeEvent e) -> {
            update(curX, curY = (double) jSpinner2.getValue());
        });
    }
    
    private void update(double nx, double ny) {
        //if (s instanceof RectSelection) {
            //RectSelection ss = (RectSelection) s;
            Rectangle2D.Float rect = (Rectangle2D.Float) s.scaledRect;
            rect.setRect(x1, y1, nx, ny);
//        } else {
//            LineSelection ss = (LineSelection) s;
//            Line2D.Float line = (Line2D.Float) ss.line;
//            line.setLine(x1, y1, nx, y2);
//        }
        surface.repaint();
    }
    
    public void cancel() {
        update(x2, y2);
    }
    
    public void accept(Dimension pageSize) {
        DbHelper.updateSelectionLocation(s, surface);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();

        jLabel1.setText("العرض:");

        jLabel2.setText("الطول:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
}
