//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DorrahShahed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DorrahShahed()
        {
            this.Morag3ah_DorrahShahed = new HashSet<Morag3ah_DorrahShahed>();
        }
    
        public int DetailID { get; set; }
        public int BeitID { get; set; }
        public short BeitPart { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Dorrah Dorrah { get; set; }
        public virtual MawdeaKhlafDetail MawdeaKhlafDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Morag3ah_DorrahShahed> Morag3ah_DorrahShahed { get; set; }
    }
}
