//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khlaf
    {
        public int RewayahID { get; set; }
        public bool HasKholf { get; set; }
        public int KhlafGroupID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual KhlafGroup KhlafGroup { get; set; }
        public virtual Rewayah Rewayah { get; set; }
    }
}
