//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MawdeaKhlaf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MawdeaKhlaf()
        {
            this.MawdeaKhlafDetail = new HashSet<MawdeaKhlafDetail>();
            this.Morag3ah_MawdeaKhlaf = new HashSet<Morag3ah_MawdeaKhlaf>();
        }
    
        public int C_ID { get; set; }
        public int PageNumber { get; set; }
        public int DetailID { get; set; }
        public Nullable<float> x1 { get; set; }
        public Nullable<float> x2 { get; set; }
        public Nullable<float> y1 { get; set; }
        public Nullable<float> y2 { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MawdeaKhlafDetail> MawdeaKhlafDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Morag3ah_MawdeaKhlaf> Morag3ah_MawdeaKhlaf { get; set; }
    }
}
