//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MawdeaKhlafDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MawdeaKhlafDetail()
        {
            this.DorrahShahed = new HashSet<DorrahShahed>();
            this.KhlafGroup = new HashSet<KhlafGroup>();
            this.ShatibiyyahShahed = new HashSet<ShatibiyyahShahed>();
            this.Morag3ah_MawdeaKhlafDetail = new HashSet<Morag3ah_MawdeaKhlafDetail>();
        }
    
        public int C_ID { get; set; }
        public Nullable<int> OwnerMawdeaKhlaf { get; set; }
        public int KhlafType { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DorrahShahed> DorrahShahed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhlafGroup> KhlafGroup { get; set; }
        public virtual MawdeaKhlaf MawdeaKhlaf { get; set; }
        public virtual MawdeaKhlafType MawdeaKhlafType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShatibiyyahShahed> ShatibiyyahShahed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Morag3ah_MawdeaKhlafDetail> Morag3ah_MawdeaKhlafDetail { get; set; }
    }
}
