//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mushaf_qeraat_serverEntities : DbContext
    {
        public mushaf_qeraat_serverEntities()
            : base("name=mushaf_qeraat_serverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dorrah> Dorrah { get; set; }
        public virtual DbSet<DorrahPage> DorrahPage { get; set; }
        public virtual DbSet<DorrahSearch> DorrahSearch { get; set; }
        public virtual DbSet<DorrahShahed> DorrahShahed { get; set; }
        public virtual DbSet<DorrahTitle> DorrahTitle { get; set; }
        public virtual DbSet<Khlaf> Khlaf { get; set; }
        public virtual DbSet<KhlafGroup> KhlafGroup { get; set; }
        public virtual DbSet<MawdeaKhlaf> MawdeaKhlaf { get; set; }
        public virtual DbSet<MawdeaKhlafDetail> MawdeaKhlafDetail { get; set; }
        public virtual DbSet<MawdeaKhlafType> MawdeaKhlafType { get; set; }
        public virtual DbSet<OsolIntro> OsolIntro { get; set; }
        public virtual DbSet<Qeraah> Qeraah { get; set; }
        public virtual DbSet<QeraahGroup> QeraahGroup { get; set; }
        public virtual DbSet<Rewayah> Rewayah { get; set; }
        public virtual DbSet<Shatibiyyah> Shatibiyyah { get; set; }
        public virtual DbSet<ShatibiyyahPage> ShatibiyyahPage { get; set; }
        public virtual DbSet<ShatibiyyahSearch> ShatibiyyahSearch { get; set; }
        public virtual DbSet<ShatibiyyahShahed> ShatibiyyahShahed { get; set; }
        public virtual DbSet<ShatibiyyahTitle> ShatibiyyahTitle { get; set; }
        public virtual DbSet<Submit_DorrahShahed> Submit_DorrahShahed { get; set; }
        public virtual DbSet<Submit_Khlaf> Submit_Khlaf { get; set; }
        public virtual DbSet<Submit_KhlafGroup> Submit_KhlafGroup { get; set; }
        public virtual DbSet<Submit_MawdeaKhlaf> Submit_MawdeaKhlaf { get; set; }
        public virtual DbSet<Submit_MawdeaKhlafDetail> Submit_MawdeaKhlafDetail { get; set; }
        public virtual DbSet<Submit_ShatibiyyahShahed> Submit_ShatibiyyahShahed { get; set; }
        public virtual DbSet<SubmitRejectReason> SubmitRejectReason { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserSubmit> UserSubmit { get; set; }
        public virtual DbSet<Morag3ah_DorrahShahed> Morag3ah_DorrahShahed { get; set; }
        public virtual DbSet<Morag3ah_MawdeaKhlaf> Morag3ah_MawdeaKhlaf { get; set; }
        public virtual DbSet<Morag3ah_MawdeaKhlafDetail> Morag3ah_MawdeaKhlafDetail { get; set; }
        public virtual DbSet<Morag3ah_ShatibiyyahShahed> Morag3ah_ShatibiyyahShahed { get; set; }
        public virtual DbSet<RowMorag3ahType> RowMorag3ahType { get; set; }
        public virtual DbSet<UserMorag3ah> UserMorag3ah { get; set; }
    }
}
