//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Morag3ah_MawdeaKhlaf
    {
        public int ID { get; set; }
        public int Morag3ahID { get; set; }
        public int MawdeaKhlafID { get; set; }
        public int Type { get; set; }
        public Nullable<int> Old_PageNumber { get; set; }
        public Nullable<int> Old_DetailID { get; set; }
        public Nullable<float> Old_x1 { get; set; }
        public Nullable<float> Old_x2 { get; set; }
        public Nullable<float> Old_y1 { get; set; }
        public Nullable<float> Old_y2 { get; set; }
    
        public virtual MawdeaKhlaf MawdeaKhlaf { get; set; }
        public virtual RowMorag3ahType RowMorag3ahType { get; set; }
        public virtual UserMorag3ah UserMorag3ah { get; set; }
    }
}
