//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Morag3ah_DorrahShahed
    {
        public int ID { get; set; }
        public int Morag3ahID { get; set; }
        public int DetailID { get; set; }
        public int BeitID { get; set; }
        public int Type { get; set; }
    
        public virtual DorrahShahed DorrahShahed { get; set; }
        public virtual RowMorag3ahType RowMorag3ahType { get; set; }
        public virtual UserMorag3ah UserMorag3ah { get; set; }
    }
}
