//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShatibiyyahSearch
    {
        public int BeitID { get; set; }
        public string BeitText { get; set; }
    
        public virtual Shatibiyyah Shatibiyyah { get; set; }
    }
}
