//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shatibiyyah
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shatibiyyah()
        {
            this.ShatibiyyahShahed = new HashSet<ShatibiyyahShahed>();
        }
    
        public int C_ID { get; set; }
        public string Part1 { get; set; }
        public string Part2 { get; set; }
    
        public virtual ShatibiyyahPage ShatibiyyahPage { get; set; }
        public virtual ShatibiyyahSearch ShatibiyyahSearch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShatibiyyahShahed> ShatibiyyahShahed { get; set; }
        public virtual ShatibiyyahTitle ShatibiyyahTitle { get; set; }
    }
}
