//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submit_MawdeaKhlafDetail
    {
        public int ID { get; set; }
        public int SubmitID { get; set; }
        public int TableID { get; set; }
        public Nullable<int> OwnerMawdeaKhlaf { get; set; }
        public int DetailType { get; set; }
        public Nullable<int> InsertedID { get; set; }
        public Nullable<int> RejectReason { get; set; }
    
        public virtual SubmitRejectReason SubmitRejectReason { get; set; }
        public virtual UserSubmit UserSubmit { get; set; }
    }
}
